[workspace]
members = [
  "my-component-a",
  "my-component-b",
  "my-component-c",
  "my-component-d",
  "my-app",
  "post-build",
]

[profile.release]
panic = 'abort'
codegen-units = 1
opt-level = 'z'
lto = true
