[package]
name = "yew-style-in-rs-macro"
version = "0.4.0"
edition = "2021"
authors = ["ORITO Itsuki <orito.itsuki@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Scoped CSS for Yew"
repository = "https://github.com/MatchaChoco010/yew-style-in-rs"
homepage = "https://github.com/MatchaChoco010/yew-style-in-rs"
readme = "../../README.md"
categories = ["web-programming", "wasm", "gui"]
keywords = ["yew", "style", "css"]

[lib]
proc-macro = true

[dependencies]
anyhow = "1.0.55"
fastrand = "1.7.0"
fslock = "0.2.1"
libc = "0.2.119"
once_cell = "1.9.0"
proc-macro2 = { version = "1.0.36", features = ["span-locations"] }
quote = "1.0.15"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
syn = { version = "1.0.86", features = ["full"] }
yew-style-in-rs-core = { version = "0.4.0", path = "../yew-style-in-rs-core" }
