[package]
name = "my-component-d"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = "0.19.3"
yew-style-in-rs = { path = "../../packages/yew-style-in-rs" }

[features]
default = []
dry-run = ["yew-style-in-rs/dry-run"]

[package.metadata.docs.rs]
cargo-args = ["--features=dry-run"]
