[package]
name = "yew-style-in-rs"
version = "0.1.0"
edition = "2021"
authors = ["Orito Itsuki <orito.itsuki@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Scoped CSS for Yew"
repository = "https://github.com/MatchaChoco010/yew-style-in-rs"
homepage = "https://github.com/MatchaChoco010/yew-style-in-rs"
readme = "../../README.md"
keywords = ["yew", "style", "css"]

[dependencies]
anyhow = "1.0.55"
fastrand = "1.7.0"
gloo = "0.6.1"
instant = { version = "0.1", features = ["wasm-bindgen"] }
once_cell = "1.10.0"
web-sys = { version = "0.3.56", features = [
    "HtmlHeadElement",
    "HtmlStyleElement",
]}
yew = "0.19.3"
yew-style-in-rs-core = { version = "0.2.0", path = "../yew-style-in-rs-core" }
yew-style-in-rs-macro = { version = "0.2.0", path = "../yew-style-in-rs-macro" }
