[package]
name = "yew-style-in-rs"
version = "0.1.0"
edition = "2021"
author = ["Orito Itsuki <orito.itsuki@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Scoped CSS for Yew"
repository = "https://github.com/MatchaChoco010/yew-style-in-rs"
homepage = "https://github.com/MatchaChoco010/yew-style-in-rs"
readme = "../../README.md"
keyword = ["yew", "style", "css"]

[dependencies]
anyhow = "1.0.55"
fastrand = "1.7.0"
instant = { version = "0.1", features = ["wasm-bindgen"] }
once_cell = "1.10.0"
parcel_css = "1.0.0-alpha.10"
web-sys = { version = "0.3.56", features = [
    "Window",
    "Document",
    "Element",
    "HtmlElement",
    "HtmlHeadElement",
    "HtmlStyleElement",
]}
yew = "0.19.3"
yew-style-in-rs-macro = { path = "../yew-style-in-rs-macro" }
